name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run linter
      run: npm run lint
    - name: Get code coverage
      run: npm run test:coverage
    - name: Publish coverage
      uses: actions/upload-artifact@v1.0.0
      with:
        name: code_coverage
        path: ./coverage
